FROM alpine:3.21

ARG	HOST
ARG PORT

RUN echo "[Nginx] Installing nginx and openssl"
RUN apk update && apk add --no-interactive --no-cache nginx gettext
RUN mkdir /etc/nginx/ssl && chown -R nginx:nginx /etc/nginx/ssl
#will need to create relevant directories?
#check for vault security certificates?

COPY config/nginx.conf /etc/nginx/http.d/t42bcn.conf
RUN chown -R root:root /etc/nginx/http.d/t42bcn.conf
RUN chmod -R 664 /etc/nginx/http.d/t42bcn.conf
RUN envsubst '${HOST} ${PORT}' < /etc/nginx/http.d/t42bcn.conf > /tmp/t42bcn.conf \
&& mv /tmp/t42bcn.conf /etc/nginx/http.d/t42bcn.conf 

RUN echo "[Nginx] Launching Nginx"
ENTRYPOINT ["nginx", "-g", "daemon off;"]
