FROM alpine:3.21

RUN apk update && apk add --no-interactive --no-cache npm nodejs 
COPY ./server /app/
WORKDIR /app
RUN npm init -y
RUN npm install express
RUN npm install prisma @prisma/client
RUN npm install -D prisma

ENTRYPOINT ["npm", "start"]

