FROM alpine:3.21

RUN apk update && apk add --no-interactive --no-cache npm nodejs 
COPY ./server /app/
WORKDIR /app
RUN npm install
#RUN npm install -g npm@11.7.0
RUN npm run build

ENTRYPOINT ["npm", "start"]

